### ISSUE TITLE
Break

### ISSUE THREAD

**Issue by wdeschain** [solana-labs/break#483] opened 2020-10-18 11:34 UTC
![Screenshot 2020-10-18 062612 BROKE](https://user-images.githubusercontent.com/42897241/96366239-f6ed6e80-110b-11eb-8eed-cefbf118bd53.jpg)
![Screenshot 2020-10-18 063032 BROKE TESTNET](https://user-images.githubusercontent.com/42897241/96366240-fc4ab900-110b-11eb-8215-efc469b554a0.jpg)

???

**Comment by jstarry** [comment] 2020-10-19 13:44
@wdeschain hey! thanks for creating this issue!

The issue is that the break game uses a server to forward transactions to the testnet cluster. That server was forwarding transactions too slowly and so some transactions expired (transactions are only valid for less than 2min before they expire). This issue should be fixed now!

**Closed by jstarry** 2020-10-19 13:44 UTC
